name: SonarQube Analysis

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sonarqube-analysis:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run SonarQube Scanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=devops-tools-app \
            -Dsonar.projectName="DevOps Tools Showcase" \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.sources=. \
            -Dsonar.language=py \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Wait for SonarQube quality gate (polling)
        id: qualitygate
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_HOST_URL: 'http://localhost:9000'

      - name: Fail pipeline if quality gate fails
        run: |
          echo "Quality gate status: ${{ steps.qualitygate.outputs.quality-gate-status }}"
          if [ "${{ steps.qualitygate.outputs.quality-gate-status }}" != "OK" ]; then
            echo "❌ SonarQube quality gate failed. Exiting with status 1."
            curl -X POST -H 'Content-Type: application/json' \
              -d '{"text":"❌ SonarQube analysis failed due to issues detected. Pipeline stopped."}' \
              ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
            exit 1
          else
            echo "✅ SonarQube quality gate passed successfully."
            curl -X POST -H 'Content-Type: application/json' \
              -d '{"text":"✅ SonarQube analysis passed. No critical issues found."}' \
              ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
